/**
 * generated by Xtext 2.11.0
 */
package dk.sdu.mdsd.ann;

import dk.sdu.mdsd.ann.AbstractAnnRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class AnnRuntimeModule extends AbstractAnnRuntimeModule {
}
