/**
 * generated by Xtext 2.11.0
 */
package dk.sdu.mdsd.ann;

import dk.sdu.mdsd.ann.AnnStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class AnnStandaloneSetup extends AnnStandaloneSetupGenerated {
  public static void doSetup() {
    new AnnStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
