/**
 * generated by Xtext 2.11.0
 */
package dk.sdu.mdsd.ann.ann;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mdsd.ann.ann.Condition#getCondition <em>Condition</em>}</li>
 *   <li>{@link dk.sdu.mdsd.ann.ann.Condition#getNum2 <em>Num2</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mdsd.ann.ann.AnnPackage#getCondition()
 * @model
 * @generated
 */
public interface Condition extends EObject
{
  /**
   * Returns the value of the '<em><b>Condition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Condition</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition</em>' attribute.
   * @see #setCondition(String)
   * @see dk.sdu.mdsd.ann.ann.AnnPackage#getCondition_Condition()
   * @model
   * @generated
   */
  String getCondition();

  /**
   * Sets the value of the '{@link dk.sdu.mdsd.ann.ann.Condition#getCondition <em>Condition</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condition</em>' attribute.
   * @see #getCondition()
   * @generated
   */
  void setCondition(String value);

  /**
   * Returns the value of the '<em><b>Num2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Num2</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Num2</em>' attribute.
   * @see #setNum2(String)
   * @see dk.sdu.mdsd.ann.ann.AnnPackage#getCondition_Num2()
   * @model
   * @generated
   */
  String getNum2();

  /**
   * Sets the value of the '{@link dk.sdu.mdsd.ann.ann.Condition#getNum2 <em>Num2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Num2</em>' attribute.
   * @see #getNum2()
   * @generated
   */
  void setNum2(String value);

} // Condition
