/**
 * generated by Xtext 2.11.0
 */
package dk.sdu.mdsd.ann.ann;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Hidden</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mdsd.ann.ann.Hidden#getL_rule <em>Lrule</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mdsd.ann.ann.AnnPackage#getHidden()
 * @model
 * @generated
 */
public interface Hidden extends Layer
{
  /**
   * Returns the value of the '<em><b>Lrule</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Lrule</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lrule</em>' reference.
   * @see #setL_rule(Activation)
   * @see dk.sdu.mdsd.ann.ann.AnnPackage#getHidden_L_rule()
   * @model
   * @generated
   */
  Activation getL_rule();

  /**
   * Sets the value of the '{@link dk.sdu.mdsd.ann.ann.Hidden#getL_rule <em>Lrule</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lrule</em>' reference.
   * @see #getL_rule()
   * @generated
   */
  void setL_rule(Activation value);

} // Hidden
