/**
 * generated by Xtext 2.11.0
 */
package dk.sdu.mdsd.ann.ann;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Restriction</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mdsd.ann.ann.Restriction#getConstraint <em>Constraint</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mdsd.ann.ann.AnnPackage#getRestriction()
 * @model
 * @generated
 */
public interface Restriction extends EObject
{
  /**
   * Returns the value of the '<em><b>Constraint</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Constraint</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constraint</em>' reference.
   * @see #setConstraint(Constraint)
   * @see dk.sdu.mdsd.ann.ann.AnnPackage#getRestriction_Constraint()
   * @model
   * @generated
   */
  Constraint getConstraint();

  /**
   * Sets the value of the '{@link dk.sdu.mdsd.ann.ann.Restriction#getConstraint <em>Constraint</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Constraint</em>' reference.
   * @see #getConstraint()
   * @generated
   */
  void setConstraint(Constraint value);

} // Restriction
