/**
 * generated by Xtext 2.11.0
 */
package dk.sdu.mdsd.ann.scoping;

import dk.sdu.mdsd.ann.scoping.AbstractAnnScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class AnnScopeProvider extends AbstractAnnScopeProvider {
}
