/**
 * generated by Xtext 2.11.0
 */
package dk.sdu.mdsd.ann.ui.contentassist;

import dk.sdu.mdsd.ann.ui.contentassist.AbstractAnnProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class AnnProposalProvider extends AbstractAnnProposalProvider {
}
