/**
 * generated by Xtext 2.11.0
 */
package dk.sdu.mdsd.ann.validation;

import dk.sdu.mdsd.ann.validation.AbstractAnnValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class AnnValidator extends AbstractAnnValidator {
}
